# Generated by Django 4.0.4 on 2022-04-13 02:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tools", "0001_initial"),
        ("labs", "0001_initial"),
        ("samples", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Analysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Finished", "Finished"),
                            ("Pending", "Pending"),
                            ("In progress", "In Progress"),
                        ],
                        max_length=12,
                    ),
                ),
                ("structure", models.CharField(max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(null=True)),
                ("ended_at", models.DateTimeField(null=True)),
                (
                    "lab",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="labs.lab",
                    ),
                ),
                (
                    "laborant",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sample",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="samples.sample",
                    ),
                ),
                ("tools", models.ManyToManyField(to="tools.tool")),
            ],
        ),
    ]
