# Generated by Django 4.0.4 on 2022-04-16 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analysis",
            name="structure",
            field=models.TextField(null=True),
        ),
    ]
